// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// unified_kappa_continuous_rcpp
Rcpp::List unified_kappa_continuous_rcpp(const Rcpp::NumericMatrix& x_r, std::string method, std::string weight_type);
RcppExport SEXP _misskappa_unified_kappa_continuous_rcpp(SEXP x_rSEXP, SEXP methodSEXP, SEXP weight_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(unified_kappa_continuous_rcpp(x_r, method, weight_type));
    return rcpp_result_gen;
END_RCPP
}
// unified_kappa_raw_rcpp
Rcpp::List unified_kappa_raw_rcpp(const Rcpp::IntegerMatrix& x_r, std::string method, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values, Rcpp::List options);
RcppExport SEXP _misskappa_unified_kappa_raw_rcpp(SEXP x_rSEXP, SEXP methodSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(unified_kappa_raw_rcpp(x_r, method, weight_type, values, options));
    return rcpp_result_gen;
END_RCPP
}
// unified_kappa_counts_rcpp
Rcpp::List unified_kappa_counts_rcpp(const Rcpp::IntegerMatrix& x_r, int r, std::string method, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values, Rcpp::List options);
RcppExport SEXP _misskappa_unified_kappa_counts_rcpp(SEXP x_rSEXP, SEXP rSEXP, SEXP methodSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(unified_kappa_counts_rcpp(x_r, r, method, weight_type, values, options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_misskappa_unified_kappa_continuous_rcpp", (DL_FUNC) &_misskappa_unified_kappa_continuous_rcpp, 3},
    {"_misskappa_unified_kappa_raw_rcpp", (DL_FUNC) &_misskappa_unified_kappa_raw_rcpp, 5},
    {"_misskappa_unified_kappa_counts_rcpp", (DL_FUNC) &_misskappa_unified_kappa_counts_rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_misskappa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
