# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Unified C++ Backend for Continuous Data Kappa
#' @keywords internal
unified_kappa_continuous_rcpp <- function(x_r, method, weight_type) {
    .Call(`_misskappa_unified_kappa_continuous_rcpp`, x_r, method, weight_type)
}

#' Unified C++ Backend for Raw Categorical Data Kappa
#' @keywords internal
unified_kappa_raw_rcpp <- function(x_r, method, weight_type, values, options) {
    .Call(`_misskappa_unified_kappa_raw_rcpp`, x_r, method, weight_type, values, options)
}

#' Unified C++ Backend for Counts Data Kappa
#' @keywords internal
unified_kappa_counts_rcpp <- function(x_r, r, method, weight_type, values, options) {
    .Call(`_misskappa_unified_kappa_counts_rcpp`, x_r, r, method, weight_type, values, options)
}

