#!/usr/bin/env bash
# Vendor the C++ library into the R package.
#
# The canonical C++ lives at <repo>/src (implementation) and <repo>/include
# (public headers). For local dev that is enough — the CMake build links the
# unit tests, and `r-package/src/Makevars` used to reach up to ../../include and
# a prebuilt ../../build-opt/libmisskappa.a. That reach-up breaks the moment the
# package is installed on its own (remotes::install_github, CRAN, a tarball),
# because only r-package/ ships.
#
# This script makes the package self-contained: it copies the canonical sources
# into r-package/src/ so R compiles them directly. The canonical tree stays the
# single source of truth — every file written here carries a @generated banner
# and is overwritten on the next run, so NEVER edit the vendored copies. After
# any change under src/ or include/, re-run this (or `just vendor`, which the R
# recipes depend on).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # repo root
src_dir="$here/src"
inc_dir="$here/include/misskappa"
dest="$here/r-package/src"
marker="// @generated by dev/vendor-cpp.sh"

# 1. Drop anything a previous run generated (identified by the banner), so
#    renamed or deleted canonical sources leave no stale copy behind. Files with
#    no banner — rcpp_glue.cpp, RcppExports.cpp, Makevars — are left untouched.
while IFS= read -r -d '' f; do
  if IFS= read -r first < "$f" && [[ "$first" == "$marker"* ]]; then
    rm -f "$f"
  fi
done < <(find "$dest" -type f \( -name '*.cpp' -o -name '*.hpp' \) -print0)
rmdir "$dest/misskappa" 2>/dev/null || true

# 2. Copy fresh, each stamped with a banner pointing back at its source.
vendor() {  # vendor <src-file> <dest-file>
  local s="$1" d="$2" rel
  rel="$(realpath --relative-to="$here" "$s")"
  mkdir -p "$(dirname "$d")"
  { printf '%s from %s — DO NOT EDIT; re-run `just vendor`.\n' "$marker" "$rel"
    cat "$s"; } > "$d"
}

count=0
for s in "$src_dir"/*.cpp "$src_dir"/*.hpp; do
  vendor "$s" "$dest/$(basename "$s")"
  count=$((count + 1))
done
for s in "$inc_dir"/*.hpp; do
  vendor "$s" "$dest/misskappa/$(basename "$s")"
  count=$((count + 1))
done

echo "vendored $count file(s) into r-package/src/ (with misskappa/ headers)"
