// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KappasRawCpp
Rcpp::List KappasRawCpp(const arma::mat& x, double c1, Rcpp::String transform_str, double conf_level, Rcpp::String alternative_str, bool bootstrap, int n_reps, Rcpp::Nullable<int> seed);
RcppExport SEXP _quadagree_KappasRawCpp(SEXP xSEXP, SEXP c1SEXP, SEXP transform_strSEXP, SEXP conf_levelSEXP, SEXP alternative_strSEXP, SEXP bootstrapSEXP, SEXP n_repsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type transform_str(transform_strSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type alternative_str(alternative_strSEXP);
    Rcpp::traits::input_parameter< bool >::type bootstrap(bootstrapSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(KappasRawCpp(x, c1, transform_str, conf_level, alternative_str, bootstrap, n_reps, seed));
    return rcpp_result_gen;
END_RCPP
}
// KappasAggrCpp
Rcpp::List KappasAggrCpp(const arma::mat& x, const arma::vec& values, int R, double c1, Rcpp::String transform_str, double conf_level, Rcpp::String alternative_str, bool bootstrap, int n_reps, Rcpp::Nullable<int> seed);
RcppExport SEXP _quadagree_KappasAggrCpp(SEXP xSEXP, SEXP valuesSEXP, SEXP RSEXP, SEXP c1SEXP, SEXP transform_strSEXP, SEXP conf_levelSEXP, SEXP alternative_strSEXP, SEXP bootstrapSEXP, SEXP n_repsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type transform_str(transform_strSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type alternative_str(alternative_strSEXP);
    Rcpp::traits::input_parameter< bool >::type bootstrap(bootstrapSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(KappasAggrCpp(x, values, R, c1, transform_str, conf_level, alternative_str, bootstrap, n_reps, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quadagree_KappasRawCpp", (DL_FUNC) &_quadagree_KappasRawCpp, 8},
    {"_quadagree_KappasAggrCpp", (DL_FUNC) &_quadagree_KappasAggrCpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_quadagree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
