# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Raw Kappa Calculation (C++ Core)
#' @description Computes estimates, CIs, and covariance for Fleiss', Conger's, and BP kappa.
#' @param c1 The constant for Brennan-Prediger chance agreement.
#' @keywords internal
KappasRawCpp <- function(x, c1, transform_str = "none", conf_level = 0.95, alternative_str = "two.sided", bootstrap = FALSE, n_reps = 1000L, seed = NULL) {
    .Call(`_quadagree_KappasRawCpp`, x, c1, transform_str, conf_level, alternative_str, bootstrap, n_reps, seed)
}

#' @title Aggregated Kappa Calculation (C++ Core)
#' @description Computes estimates and CIs for Fleiss' and BP kappa from aggregated data.
#' @keywords internal
KappasAggrCpp <- function(x, values, R, c1, transform_str = "none", conf_level = 0.95, alternative_str = "two.sided", bootstrap = FALSE, n_reps = 1000L, seed = NULL) {
    .Call(`_quadagree_KappasAggrCpp`, x, values, R, c1, transform_str, conf_level, alternative_str, bootstrap, n_reps, seed)
}

