// @generated by dev/vendor-cpp.sh from src/estimate_quadratic.cpp — DO NOT EDIT; re-run `just vendor`.
// Closed-form quadratic-loss estimator (Conger, Fleiss, Brennan-Prediger)
// for raw real-valued ratings.
//
// Treats categorical ratings as numeric scores; missing entries are NaN.
// Per-rater means and covariances are computed from all available entries.
// The asymptotic covariance is assembled from the influence functions of the
// three summaries used by the quadratic coefficients, avoiding the full
// fourth-moment tensor.

#include "detail_pattern_checks.hpp"
#include "misskappa/estimate.hpp"

#include <cmath>
#include <limits>
#include <utility>
#include <vector>

namespace misskappa {

namespace {

constexpr double zero_tol = 1e-9;

// Internal moment-bundle output of calculate_psi.
struct AcovResults {
  RealMat summary_cov; // 3 x 3 covariance of (t1, t2, t3) summary statistics
  RealMat summary_psi; // n x 3 per-subject IF rows for those summaries
  RealVec mu_hat;    // length R per-rater means
  RealMat sigma_hat; // R x R per-rater-pair covariances
  int R = 0;
};

// Heavy-lifter: from raw real-valued ratings + finiteness mask, compute the
// 3x3 covariance of (t1 = sum(sigma_hat), t2 = trace(sigma_hat),
// t3 = sum((mu - mean(mu))^2)) using the moment-level influence functions.
Result<AcovResults> calculate_psi(
    const RealMat& x, const Eigen::Matrix<int, Eigen::Dynamic, Eigen::Dynamic>& M,
    int n) {
  const int R = static_cast<int>(x.cols());
  AcovResults out;
  out.R = R;

  // Zero out non-finite entries in a working copy for later linear algebra.
  RealMat Xf = x;
  for (Eigen::Index i = 0; i < Xf.rows(); ++i) {
    for (Eigen::Index j = 0; j < Xf.cols(); ++j) {
      if (M(i, j) == 0) Xf(i, j) = 0.0;
    }
  }

  RealVec count = M.cast<double>().colwise().sum().transpose();  // length R
  out.mu_hat.resize(R);
  for (int j = 0; j < R; ++j) {
    if (count(j) <= zero_tol) return misskappa::unexpected(Error::invalid_argument);
    out.mu_hat(j) = (count(j) > 0) ? Xf.col(j).sum() / count(j)
                                   : std::numeric_limits<double>::quiet_NaN();
  }

  // Y_hat = X with the rater-mean subtracted, NaNs zeroed out.
  RealMat Y_hat = x;
  for (Eigen::Index i = 0; i < Y_hat.rows(); ++i) {
    for (Eigen::Index j = 0; j < Y_hat.cols(); ++j) {
      Y_hat(i, j) = M(i, j) ? (x(i, j) - out.mu_hat(j)) : 0.0;
    }
  }

  RealVec p1 = count / static_cast<double>(n);
  RealMat p2 = (M.cast<double>().transpose() * M.cast<double>()) / static_cast<double>(n);
  for (int j = 0; j < R; ++j) {
    for (int k = j; k < R; ++k) {
      if (p2(j, k) <= zero_tol) return misskappa::unexpected(Error::invalid_argument);
    }
  }

  // sigma_hat(j, k): pairwise covariance of raters j, k over rows where both observed.
  out.sigma_hat = RealMat::Zero(R, R);
  for (int j = 0; j < R; ++j) {
    for (int k = j; k < R; ++k) {
      // Find row indices where both raters observed.
      std::vector<int> idx;
      idx.reserve(n);
      for (int i = 0; i < n; ++i) {
        if (M(i, j) == 1 && M(i, k) == 1) idx.push_back(i);
      }
      if (!idx.empty()) {
        double sum_j = 0, sum_k = 0;
        for (int i : idx) { sum_j += x(i, j); sum_k += x(i, k); }
        const double mu_j_p = sum_j / idx.size();
        const double mu_k_p = sum_k / idx.size();
        double sum_prod = 0;
        for (int i : idx) {
          sum_prod += (x(i, j) - mu_j_p) * (x(i, k) - mu_k_p);
        }
        out.sigma_hat(j, k) = sum_prod / idx.size();
      }
      out.sigma_hat(k, j) = out.sigma_hat(j, k);
    }
  }

  // Assemble Psi (3 x 3 covariance of the summary influence functions).
  out.summary_cov = RealMat::Zero(3, 3);
  out.summary_psi = RealMat::Zero(n, 3);
  RealVec v_dmu = 2.0 * (out.mu_hat.array() - out.mu_hat.mean()).matrix();
  for (int row = 0; row < n; ++row) {
    RealVec phi = RealVec::Zero(3);
    for (int j = 0; j < R; ++j) {
      if (!M(row, j)) continue;
      phi(2) += (v_dmu(j) / p1(j)) * Y_hat(row, j);
      for (int k = 0; k < R; ++k) {
        if (!M(row, k)) continue;
        const double term = (Y_hat(row, j) * Y_hat(row, k) - out.sigma_hat(j, k)) / p2(j, k);
        phi(0) += term;
        if (j == k) phi(1) += term;
      }
    }
    out.summary_psi.row(row) = phi.transpose();
    out.summary_cov.noalias() += phi * phi.transpose();
  }
  out.summary_cov /= static_cast<double>(n);

  return out;
}

}  // namespace

Result<Estimation> estimate_quadratic(RealMatView ratings, const RealVec& values) {
  const int C = static_cast<int>(values.size());
  if (C < 1) return misskappa::unexpected(Error::invalid_argument);
  if (ratings.rows() < 1 || ratings.cols() < 2) {
    return misskappa::unexpected(Error::invalid_argument);
  }

  // Brennan-Prediger constant: 2 / C^2 * (C * sum(v^2) - sum(v)^2).
  const double c1 = (2.0 / (C * C)) * (C * values.squaredNorm() - std::pow(values.sum(), 2));

  const auto M_full = detail::finite_mask(ratings);
  auto identified = detail::require_complete_pair_observation(M_full);
  if (!identified) return misskappa::unexpected(identified.error());

  RealMat x_all = ratings;
  const int n = static_cast<int>(ratings.rows());
  const int R = static_cast<int>(ratings.cols());

  auto acov = calculate_psi(x_all, M_full, n);
  if (!acov) return misskappa::unexpected(acov.error());

  // Summary stats t1 = sum(Sigma), t2 = tr(Sigma), t3 = sum((mu - mean(mu))^2).
  const double t1 = acov->sigma_hat.sum();
  const double t2 = acov->sigma_hat.diagonal().sum();
  RealVec mu_dev = acov->mu_hat.array() - acov->mu_hat.mean();
  const double t3 = mu_dev.squaredNorm();

  // Numerators / denominators for Fleiss and Conger.
  const double NF = t1 - t2 - t3;
  const double DF = (R - 1.0) * (t2 + t3);
  const double NC = t1 - t2;
  const double DC = (R - 1.0) * t2 + static_cast<double>(R) * t3;

  const double fleiss_est = (std::abs(DF) > zero_tol)
                                ? NF / DF
                                : std::numeric_limits<double>::quiet_NaN();
  const double conger_est = (std::abs(DC) > zero_tol)
                                ? NC / DC
                                : std::numeric_limits<double>::quiet_NaN();
  const double d_obs = (2.0 / (R - 1.0)) * (t2 + t3 - t1 / R);
  const double bp_est = (std::abs(c1) > zero_tol)
                            ? 1.0 - d_obs / c1
                            : std::numeric_limits<double>::quiet_NaN();

  // Gradients of (Fleiss, Conger, BP) wrt (t1, t2, t3).
  RealVec gF = RealVec::Zero(3);
  RealVec gC = RealVec::Zero(3);
  RealVec gBP = RealVec::Zero(3);
  if (std::abs(DF) > zero_tol) {
    gF(0) = 1.0 / DF;
    gF(1) = (-DF - NF * (R - 1.0)) / (DF * DF);
    gF(2) = (-DF - NF * (R - 1.0)) / (DF * DF);
  }
  if (std::abs(DC) > zero_tol) {
    gC(0) = 1.0 / DC;
    gC(1) = (-DC - NC * (R - 1.0)) / (DC * DC);
    gC(2) = (-NC * static_cast<double>(R)) / (DC * DC);
  }
  if (std::abs(c1) > zero_tol) {
    const double m = -(2.0 / (c1 * (R - 1.0)));
    gBP(0) = m * (-1.0 / R);
    gBP(1) = m;
    gBP(2) = m;
  }

  // scaled_acov = G^T * psi * G, in (Fleiss, Conger, BP) order, then divide
  // by n. Reorder rows/cols to (Conger, Fleiss, BP) so the output matches
  // the misskappa raw-categorical convention.
  RealMat G(3, 3);
  G.col(0) = gF;
  G.col(1) = gC;
  G.col(2) = gBP;
  const RealMat scaled = G.transpose() * acov->summary_cov * G;  // (Fleiss, Conger, BP) ordering
  RealMat vcov_reordered(3, 3);
  const int perm[3] = {1, 0, 2};  // map (Conger, Fleiss, BP) -> (Fleiss, Conger, BP)
  for (int r = 0; r < 3; ++r) {
    for (int c = 0; c < 3; ++c) {
      vcov_reordered(r, c) = scaled(perm[r], perm[c]);
    }
  }
  const RealMat vcov = vcov_reordered / static_cast<double>(n);
  RealMat J_out(3, 3);
  J_out.row(0) = gC.transpose();
  J_out.row(1) = gF.transpose();
  J_out.row(2) = gBP.transpose();
  RealMat psi_kappa = build_psi_from_phi(acov->summary_psi, J_out);

  RealVec estimates(3);
  estimates(0) = conger_est;
  estimates(1) = fleiss_est;
  estimates(2) = bp_est;
  return Estimation{std::move(estimates), std::move(vcov), std::move(psi_kappa), {}};
}

}  // namespace misskappa
