// @generated by dev/vendor-cpp.sh from src/estimate_fiml_counts.cpp — DO NOT EDIT; re-run `just vendor`.
// FIML / EM estimator for counts-format input under exchangeable raters.
//
// Model: each subject's full data is a composition Z_i in {(z_1, ..., z_C):
// sum z_c = r_total}; we parameterise its law theta over the simplex of
// such compositions. Given full counts Z_i and a per-subject observed
// total r_i <= r_total, the observed counts N_i^obs are a uniformly-random
// subsample without replacement; the likelihood factor is the multivariate
// hypergeometric
//
//   P(N_i^obs | Z_i, r_i) = prod_c (Z_i(c) choose N_i^obs(c)) / (r_total choose r_i).
//
// The (r_total choose r_i) factor is constant in theta and dropped. EM
// alternates between the posterior over completions e (e + N_i^obs = Z_i)
// and the renormalised theta update. Louis observed-information on the
// pruned reference-removed parametrisation gives the asymptotic
// covariance of theta_hat; a closed-form delta-method composition maps it
// onto the (Fleiss, Brennan-Prediger) covariance.
//
// Ported from dev/legacy/misskappa/src/emdiscrete.cpp (counts branch) +
// kappaml.cpp (kappa_counts), but using the agreement-matrix input
// convention shared with the rest of the misskappa C++ API (L = 1 - W is
// computed internally).

#include "misskappa/estimate.hpp"

#include "detail_psd_inverse.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <map>
#include <unordered_map>
#include <vector>

namespace misskappa {

namespace {

constexpr double zero_tol = 1e-9;
constexpr double singular_tol = 1e-12;

// --- Binomial coefficient table ----------------------------------------------

struct Binomial {
  std::vector<std::vector<std::uint64_t>> memo;
  explicit Binomial(int max_n)
      : memo(static_cast<std::size_t>(max_n + 1),
             std::vector<std::uint64_t>(static_cast<std::size_t>(max_n + 1), 0)) {}
  std::uint64_t at(int n, int k) {
    if (k < 0 || k > n) return 0;
    if (k == 0 || k == n) return 1;
    if (k > n / 2) k = n - k;
    auto& cell = memo[static_cast<std::size_t>(n)][static_cast<std::size_t>(k)];
    if (cell != 0) return cell;
    cell = at(n - 1, k - 1) + at(n - 1, k);
    return cell;
  }
};

// --- Composition rank / unrank (lexicographic order) -------------------------
//
// rank/unrank place a total order on compositions of `n` into `c` non-negative
// integers summing to n. Each cell in the lookup is computed once via
// Binomial::at.

std::uint64_t rank_composition(const std::vector<int>& v, int n, int c, Binomial& B) {
  std::uint64_t rank = 0;
  int remaining = n;
  for (int i = 0; i < c - 1; ++i) {
    const int vi = v[static_cast<std::size_t>(i)];
    for (int j = 0; j < vi; ++j) {
      rank += B.at(remaining - j + (c - 1 - i), c - 1 - i);
    }
    remaining -= vi;
  }
  return rank;
}

std::vector<int> unrank_composition(std::uint64_t rank, int n, int c, Binomial& B) {
  std::vector<int> v(static_cast<std::size_t>(c), 0);
  int remaining = n;
  std::uint64_t r = rank;
  for (int i = 0; i < c - 1; ++i) {
    if (remaining == 0) break;
    int count = 0;
    while (true) {
      const std::uint64_t block = B.at(remaining - count + c - 1 - i, c - 1 - i);
      if (r < block) break;
      r -= block;
      ++count;
    }
    v[static_cast<std::size_t>(i)] = count;
    remaining -= count;
  }
  if (remaining > 0) v[static_cast<std::size_t>(c - 1)] = remaining;
  return v;
}

// All compositions of n into c non-negative integers.
void enumerate_compositions_recursive(
    int n, int c, std::vector<int>& cur, std::size_t pos,
    std::vector<std::vector<int>>& out) {
  if (pos + 1 == static_cast<std::size_t>(c)) {
    cur[pos] = n;
    out.push_back(cur);
    return;
  }
  for (int i = 0; i <= n; ++i) {
    cur[pos] = i;
    enumerate_compositions_recursive(n - i, c, cur, pos + 1, out);
  }
}

std::vector<std::vector<int>> enumerate_compositions(int n, int c) {
  std::vector<std::vector<int>> out;
  if (c <= 0) return out;
  std::vector<int> cur(static_cast<std::size_t>(c), 0);
  enumerate_compositions_recursive(n, c, cur, 0, out);
  return out;
}

// --- Internal EM types -------------------------------------------------------
//
// "Group" = unique observed counts row; multiple subjects share a group when
// their counts match. For each group we precompute the indices of all
// compatible full compositions (in the active rank space) plus their
// multivariate-hypergeometric coefficients.

struct EmInputCounts {
  std::size_t n_active = 0;
  int c = 0;
  int r_total = 0;
  std::vector<std::uint32_t> group_n_subjects;
  std::vector<std::uint32_t> group_offsets;
  std::vector<std::uint32_t> group_n_completions;
  std::vector<std::uint32_t> completion_indices;   // index into active_ranks
  std::vector<double> mvhg_coeffs;                 // length sum(group_n_completions)
  std::vector<std::uint64_t> active_ranks;         // active idx -> global composition rank
  std::vector<std::uint32_t> subject_groups;
};

struct EmRunResultCounts {
  Eigen::VectorXd theta_hat;
  RealMat vcov;
  std::vector<std::uint64_t> pattern_ranks;  // global ranks of surviving patterns
  std::vector<std::uint64_t> pruned_active_indices;
  int c = 0;
  int r_total = 0;
  int iterations = 0;
  bool converged = false;
  std::size_t n_subjects = 0;
};

struct LouisReducedInfoCounts {
  RealMat info_star;
  RealMat jacobian;
  RealMat group_scores;
  Eigen::Index ref = 0;
};

Result<EmInputCounts> preprocess_counts(IntMatView counts, int r_total) {
  if (counts.rows() == 0 || counts.cols() == 0) {
    return std::unexpected(Error::invalid_argument);
  }
  EmInputCounts in;
  in.c = static_cast<int>(counts.cols());
  in.r_total = r_total;

  // Validate counts: non-negative, row sum <= r_total.
  for (Eigen::Index i = 0; i < counts.rows(); ++i) {
    int row_sum = 0;
    for (Eigen::Index k = 0; k < counts.cols(); ++k) {
      const int v = counts(i, k);
      if (v < 0) return std::unexpected(Error::invalid_argument);
      row_sum += v;
    }
    if (row_sum > r_total) return std::unexpected(Error::invalid_argument);
  }

  Binomial B(r_total + in.c + 1);

  // Bucket subjects by unique observed row.
  std::map<std::vector<int>, std::uint32_t> by_row;
  std::vector<std::vector<int>> pattern_order;
  std::vector<std::vector<int>> subject_rows;
  pattern_order.reserve(static_cast<std::size_t>(counts.rows()));
  subject_rows.reserve(static_cast<std::size_t>(counts.rows()));
  for (Eigen::Index i = 0; i < counts.rows(); ++i) {
    std::vector<int> row(static_cast<std::size_t>(in.c));
    for (int k = 0; k < in.c; ++k) {
      row[static_cast<std::size_t>(k)] = counts(i, k);
    }
    subject_rows.push_back(row);
    auto it = by_row.find(row);
    if (it == by_row.end()) {
      by_row.emplace(row, std::uint32_t{1});
      pattern_order.push_back(std::move(row));
    } else {
      it->second += 1;
    }
  }

  // For each unique observed row, enumerate compatible completions.
  std::map<int, std::vector<std::vector<int>>> completions_cache;  // by missing count s
  std::vector<std::uint64_t> active_ranks_raw;
  std::vector<std::vector<std::uint64_t>> group_ranks_raw;
  std::vector<std::vector<double>> group_coeffs_raw;
  group_ranks_raw.reserve(pattern_order.size());
  group_coeffs_raw.reserve(pattern_order.size());
  std::size_t total_completion_count = 0;

  for (const auto& obs : pattern_order) {
    int r_obs = 0;
    for (int v : obs) r_obs += v;
    const int s = r_total - r_obs;

    auto cached = completions_cache.find(s);
    if (cached == completions_cache.end()) {
      cached = completions_cache.emplace(s, enumerate_compositions(s, in.c)).first;
    }
    const auto& exts = cached->second;

    std::vector<std::uint64_t> g_ranks;
    std::vector<double> g_coeffs;
    g_ranks.reserve(exts.size());
    g_coeffs.reserve(exts.size());
    std::vector<int> z(static_cast<std::size_t>(in.c));
    for (const auto& ext : exts) {
      for (int k = 0; k < in.c; ++k) {
        z[static_cast<std::size_t>(k)] = obs[static_cast<std::size_t>(k)]
                                         + ext[static_cast<std::size_t>(k)];
      }
      const std::uint64_t rk = rank_composition(z, r_total, in.c, B);
      active_ranks_raw.push_back(rk);
      g_ranks.push_back(rk);

      double prod = 1.0;
      for (int k = 0; k < in.c; ++k) {
        prod *= static_cast<double>(B.at(z[static_cast<std::size_t>(k)],
                                          obs[static_cast<std::size_t>(k)]));
      }
      g_coeffs.push_back(prod);
    }
    total_completion_count += g_ranks.size();
    group_ranks_raw.push_back(std::move(g_ranks));
    group_coeffs_raw.push_back(std::move(g_coeffs));
  }

  // Active rank space: only compositions reachable from at least one observed
  // row stay in theta's support.
  std::sort(active_ranks_raw.begin(), active_ranks_raw.end());
  active_ranks_raw.erase(
      std::unique(active_ranks_raw.begin(), active_ranks_raw.end()),
      active_ranks_raw.end());
  in.active_ranks = std::move(active_ranks_raw);
  std::unordered_map<std::uint64_t, std::uint32_t> rank_to_active;
  rank_to_active.reserve(in.active_ranks.size());
  for (std::size_t i = 0; i < in.active_ranks.size(); ++i) {
    rank_to_active.emplace(in.active_ranks[i], static_cast<std::uint32_t>(i));
  }
  in.n_active = in.active_ranks.size();

  // Pack group bookkeeping.
  in.group_n_subjects.reserve(pattern_order.size());
  in.group_offsets.reserve(pattern_order.size());
  in.group_n_completions.reserve(pattern_order.size());
  in.completion_indices.reserve(total_completion_count);
  in.mvhg_coeffs.reserve(total_completion_count);
  std::map<std::vector<int>, std::uint32_t> row_to_group;
  std::uint32_t cum_offset = 0;
  for (std::size_t g = 0; g < pattern_order.size(); ++g) {
    row_to_group.emplace(pattern_order[g], static_cast<std::uint32_t>(g));
    const std::uint32_t subj_count = by_row.at(pattern_order[g]);
    in.group_n_subjects.push_back(subj_count);
    in.group_offsets.push_back(cum_offset);
    const auto& g_ranks = group_ranks_raw[g];
    const auto& g_coeffs = group_coeffs_raw[g];
    in.group_n_completions.push_back(static_cast<std::uint32_t>(g_ranks.size()));
    for (std::size_t k = 0; k < g_ranks.size(); ++k) {
      in.completion_indices.push_back(rank_to_active.at(g_ranks[k]));
      in.mvhg_coeffs.push_back(g_coeffs[k]);
    }
    cum_offset += static_cast<std::uint32_t>(g_ranks.size());
  }
  in.subject_groups.reserve(subject_rows.size());
  for (const auto& row : subject_rows) {
    in.subject_groups.push_back(row_to_group.at(row));
  }

  return in;
}

// --- EM loop -----------------------------------------------------------------

Eigen::VectorXd initialise_theta(const EmInputCounts& in, double start_alpha) {
  Eigen::VectorXd theta = Eigen::VectorXd::Constant(
      static_cast<Eigen::Index>(in.n_active), start_alpha);
  if (in.n_active == 0) return theta;
  for (std::size_t g = 0; g < in.group_n_subjects.size(); ++g) {
    const std::uint32_t n_subs = in.group_n_subjects[g];
    const std::uint32_t n_comps = in.group_n_completions[g];
    if (n_comps == 0) continue;
    const std::uint32_t offset = in.group_offsets[g];
    const double weight = static_cast<double>(n_subs) / static_cast<double>(n_comps);
    for (std::uint32_t k = 0; k < n_comps; ++k) {
      theta(static_cast<Eigen::Index>(in.completion_indices[offset + k])) += weight;
    }
  }
  const double sum = theta.sum();
  if (sum < zero_tol) return Eigen::VectorXd::Zero(theta.size());
  theta /= sum;
  return theta;
}

struct EmIterStatus {
  int iterations = 0;
  bool converged = false;
};

EmIterStatus run_em_iterations(
    Eigen::VectorXd& theta, const EmInputCounts& in, EmOptions opts) {
  EmIterStatus status;
  std::size_t n_total = 0;
  for (std::uint32_t s : in.group_n_subjects) n_total += s;
  if (n_total == 0) {
    status.converged = true;
    return status;
  }
  Eigen::VectorXd expected = Eigen::VectorXd::Zero(theta.size());
  for (int it = 0; it < opts.max_iter; ++it) {
    status.iterations = it + 1;
    expected.setZero();
    for (std::size_t g = 0; g < in.group_n_subjects.size(); ++g) {
      const std::uint32_t n_comps = in.group_n_completions[g];
      if (n_comps == 0) continue;
      const std::uint32_t offset = in.group_offsets[g];
      // weights = mvhg * theta on this group's completions.
      double sum_w = 0.0;
      for (std::uint32_t k = 0; k < n_comps; ++k) {
        const Eigen::Index idx = static_cast<Eigen::Index>(in.completion_indices[offset + k]);
        sum_w += in.mvhg_coeffs[offset + k] * theta(idx);
      }
      if (sum_w <= singular_tol) continue;
      const double scale = static_cast<double>(in.group_n_subjects[g]) / sum_w;
      for (std::uint32_t k = 0; k < n_comps; ++k) {
        const Eigen::Index idx = static_cast<Eigen::Index>(in.completion_indices[offset + k]);
        expected(idx) += scale * in.mvhg_coeffs[offset + k] * theta(idx);
      }
    }
    const double total = expected.sum();
    if (total > singular_tol) {
      expected /= total;
    } else {
      expected.setConstant(1.0 / static_cast<double>(theta.size()));
    }
    const double max_change = (expected - theta).cwiseAbs().maxCoeff();
    if (max_change < opts.tol) {
      theta.swap(expected);
      status.converged = true;
      return status;
    }
    theta.swap(expected);
  }
  return status;
}

// Louis observed information on the (n_final - 1)-dim reference-removed
// parametrisation (drops the largest-mass entry to enforce the sum-to-1
// constraint), then expands back to the full n_final dim via the Jacobian.
RealMat constraint_jacobian(Eigen::Index n_final, Eigen::Index ref) {
  if (n_final <= 1) return RealMat::Zero(n_final, 0);

  RealMat J = RealMat::Zero(n_final, n_final - 1);
  Eigen::Index w = 0;
  for (Eigen::Index i = 0; i < n_final; ++i) {
    if (i == ref) continue;
    J(i, w++) = 1.0;
  }
  for (Eigen::Index j = 0; j < n_final - 1; ++j) J(ref, j) = -1.0;
  return J;
}

LouisReducedInfoCounts build_louis_reduced_info(
    const Eigen::VectorXd& theta_pruned,
    const std::vector<std::uint64_t>& pruned_active_indices,
    const EmInputCounts& in) {
  LouisReducedInfoCounts out;
  const Eigen::Index n_final = theta_pruned.size();
  if (n_final <= 1) {
    out.info_star = RealMat::Zero(0, 0);
    out.jacobian = RealMat::Zero(n_final, 0);
    out.group_scores = RealMat::Zero(
        static_cast<Eigen::Index>(in.group_n_subjects.size()), 0);
    return out;
  }

  Eigen::Index ref = 0;
  for (Eigen::Index i = 1; i < n_final; ++i) {
    if (theta_pruned(i) > theta_pruned(ref)) ref = i;
  }
  out.ref = ref;
  std::vector<Eigen::Index> active_to_pruned(in.n_active, Eigen::Index{-1});
  for (Eigen::Index i = 0; i < n_final; ++i) {
    active_to_pruned[static_cast<std::size_t>(
        pruned_active_indices[static_cast<std::size_t>(i)])] = i;
  }

  RealMat info_star = RealMat::Zero(n_final - 1, n_final - 1);
  RealMat group_scores = RealMat::Zero(
      static_cast<Eigen::Index>(in.group_n_subjects.size()), n_final - 1);

  for (std::size_t g = 0; g < in.group_n_subjects.size(); ++g) {
    const std::uint32_t n_comps = in.group_n_completions[g];
    const std::uint32_t offset = in.group_offsets[g];

    double sum_w = 0.0;
    bool has_pruned_completion = false;
    for (std::uint32_t k = 0; k < n_comps; ++k) {
      const auto aidx = static_cast<std::size_t>(in.completion_indices[offset + k]);
      const Eigen::Index idx = active_to_pruned[aidx];
      if (idx >= 0) {
        has_pruned_completion = true;
        sum_w += in.mvhg_coeffs[offset + k] * theta_pruned(idx);
      }
    }
    if (!has_pruned_completion || sum_w <= singular_tol) continue;

    double ref_score = 0.0;
    Eigen::VectorXd s_reduced = Eigen::VectorXd::Zero(n_final - 1);
    for (std::uint32_t k = 0; k < n_comps; ++k) {
      const auto aidx = static_cast<std::size_t>(in.completion_indices[offset + k]);
      const Eigen::Index idx = active_to_pruned[aidx];
      if (idx < 0) continue;
      const double score = in.mvhg_coeffs[offset + k] / sum_w;
      if (idx == ref) {
        ref_score = score;
      } else {
        const Eigen::Index reduced_idx = (idx < ref) ? idx : idx - 1;
        s_reduced(reduced_idx) = score;
      }
    }
    if (ref_score != 0.0) s_reduced.array() -= ref_score;
    group_scores.row(static_cast<Eigen::Index>(g)) = s_reduced.transpose();
    info_star.noalias() += static_cast<double>(in.group_n_subjects[g])
                          * s_reduced * s_reduced.transpose();
  }

  out.info_star = 0.5 * (info_star + info_star.transpose());
  out.jacobian = constraint_jacobian(n_final, ref);
  out.group_scores = std::move(group_scores);
  return out;
}

RealMat em_variance(
    const Eigen::VectorXd& theta_pruned,
    const std::vector<std::uint64_t>& pruned_active_indices,
    const EmInputCounts& in,
    const EmOptions& opts) {
  const LouisReducedInfoCounts info =
      build_louis_reduced_info(theta_pruned, pruned_active_indices, in);
  if (theta_pruned.size() <= 1) return RealMat::Zero(theta_pruned.size(), theta_pruned.size());

  const RealMat var_star = detail::pseudo_inverse_psd(info.info_star, opts.info_rcond);
  return info.jacobian * var_star * info.jacobian.transpose();
}

Result<EmRunResultCounts> run_em_preprocessed(
    const EmInputCounts& in, EmOptions opts) {
  EmRunResultCounts out;
  out.c = in.c;
  out.r_total = in.r_total;
  for (std::uint32_t s : in.group_n_subjects) out.n_subjects += s;

  if (in.n_active == 0) {
    out.converged = true;
    return out;
  }
  Eigen::VectorXd theta = initialise_theta(in, opts.start_alpha);
  const EmIterStatus status = run_em_iterations(theta, in, opts);
  out.iterations = status.iterations;
  out.converged = status.converged;
  if (!out.converged) return std::unexpected(Error::not_converged);

  // Prune low-mass entries.
  std::vector<std::uint64_t> pruned_active;
  std::vector<double> pruned_theta;
  pruned_active.reserve(static_cast<std::size_t>(theta.size()));
  pruned_theta.reserve(static_cast<std::size_t>(theta.size()));
  for (Eigen::Index i = 0; i < theta.size(); ++i) {
    if (theta(i) > opts.prune_tol) {
      pruned_active.push_back(static_cast<std::uint64_t>(i));
      pruned_theta.push_back(theta(i));
    }
  }
  if (pruned_active.empty()) return std::unexpected(Error::numerical_error);

  Eigen::VectorXd tp = Eigen::Map<Eigen::VectorXd>(
      pruned_theta.data(), static_cast<Eigen::Index>(pruned_theta.size()));
  const double s = tp.sum();
  if (s < zero_tol) return std::unexpected(Error::numerical_error);
  tp /= s;

  out.theta_hat = std::move(tp);
  out.pruned_active_indices = pruned_active;
  // Map active-space indices back to global composition ranks for the
  // theta -> kappa step.
  out.pattern_ranks.reserve(pruned_active.size());
  for (std::uint64_t a : pruned_active) {
    out.pattern_ranks.push_back(in.active_ranks[static_cast<std::size_t>(a)]);
  }
  out.vcov = em_variance(out.theta_hat, pruned_active, in, opts);
  return out;
}

// --- theta_hat -> (Fleiss, BP) coefficients + delta-method vcov --------------

Estimation map_to_kappa(
    const EmRunResultCounts& em, RealMatView weights,
    const EmInputCounts& in, const EmOptions& opts) {
  const int C = static_cast<int>(weights.rows());
  const int R = em.r_total;
  const Eigen::Index n_final = em.theta_hat.size();
  const double r_pair = static_cast<double>(R) * (R - 1.0);
  const double inv_R = 1.0 / static_cast<double>(R);

  const RealMat L = RealMat::Constant(C, C, 1.0) - weights;
  const RealVec L_diag = L.diagonal();

  // Per-pattern observed disagreement d_z = (z L z - diag(L) . z) / (R(R-1)).
  // Build z's by unranking and pack into pattern_matrix (C x n_final).
  Binomial B(R + C + 1);
  RealMat pattern_matrix(C, n_final);
  RealVec d_vec(n_final);
  for (Eigen::Index j = 0; j < n_final; ++j) {
    auto z = unrank_composition(em.pattern_ranks[static_cast<std::size_t>(j)], R, C, B);
    for (int k = 0; k < C; ++k) {
      pattern_matrix(k, j) = static_cast<double>(z[static_cast<std::size_t>(k)]);
    }
    const auto zv = pattern_matrix.col(j);
    d_vec(j) = (zv.transpose() * L * zv).value() - L_diag.dot(zv);
    d_vec(j) /= r_pair;
  }

  const double d_bp = L.sum() / (static_cast<double>(C) * C);

  const Eigen::VectorXd& theta = em.theta_hat;
  const double pd = d_vec.dot(theta);                       // E_theta[d_z]
  const RealVec p_hat = (pattern_matrix * theta) * inv_R;   // length C
  const double pe_f = (p_hat.transpose() * L * p_hat).value();

  RealVec estimates(2);
  estimates(0) = (pe_f > zero_tol)
                     ? 1.0 - pd / pe_f
                     : std::numeric_limits<double>::quiet_NaN();
  estimates(1) = (d_bp > zero_tol)
                     ? 1.0 - pd / d_bp
                     : std::numeric_limits<double>::quiet_NaN();

  // Jacobian rows of (Fleiss, BP) wrt theta.
  RealMat jacobian = RealMat::Zero(2, theta.size());
  const Eigen::VectorXd grad_pd = d_vec;
  if (pe_f > zero_tol) {
    const RealVec grad_pe_f =
        (2.0 * inv_R) * (pattern_matrix.transpose() * (L * p_hat));
    jacobian.row(0) = (-(grad_pd * pe_f - pd * grad_pe_f).transpose()) / (pe_f * pe_f);
  }
  if (d_bp > zero_tol) {
    jacobian.row(1) = -grad_pd.transpose() / d_bp;
  }

  RealMat vcov = jacobian * em.vcov * jacobian.transpose();
  RealMat psi = RealMat::Zero(static_cast<Eigen::Index>(em.n_subjects), 2);
  const LouisReducedInfoCounts info =
      build_louis_reduced_info(em.theta_hat, em.pruned_active_indices, in);
  if (info.info_star.rows() > 0) {
    const RealMat var_star = detail::pseudo_inverse_psd(info.info_star, opts.info_rcond);
    const RealMat jacobian_reduced = jacobian * info.jacobian;
    const RealMat group_psi =
        static_cast<double>(em.n_subjects) * info.group_scores
        * var_star * jacobian_reduced.transpose();
    for (Eigen::Index i = 0; i < static_cast<Eigen::Index>(em.n_subjects); ++i) {
      psi.row(i) = group_psi.row(
          static_cast<Eigen::Index>(in.subject_groups[static_cast<std::size_t>(i)]));
    }
  }

  return Estimation{std::move(estimates), std::move(vcov), std::move(psi)};
}

}  // namespace

Result<Estimation> estimate_fiml_counts(
    IntMatView counts, RealMatView weights, int r_total, EmOptions opts) {
  if (counts.rows() < 1) return std::unexpected(Error::invalid_argument);
  if (r_total < 2) return std::unexpected(Error::invalid_argument);
  const int C = static_cast<int>(weights.rows());
  if (weights.cols() != C || counts.cols() != C) {
    return std::unexpected(Error::dimension_mismatch);
  }

  auto in_res = preprocess_counts(counts, r_total);
  if (!in_res) return std::unexpected(in_res.error());

  auto em = run_em_preprocessed(*in_res, opts);
  if (!em) return std::unexpected(em.error());
  if (em->theta_hat.size() == 0) return std::unexpected(Error::numerical_error);

  return map_to_kappa(*em, weights, *in_res, opts);
}

}  // namespace misskappa
