// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_kappa_raw
Rcpp::List rcpp_kappa_raw(const Rcpp::IntegerMatrix& x, std::string method, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values, Rcpp::List em_options);
RcppExport SEXP _misskappa_rcpp_kappa_raw(SEXP xSEXP, SEXP methodSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP, SEXP em_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type em_options(em_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_raw(x, method, weight_type, values, em_options));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_alpha_raw
Rcpp::List rcpp_alpha_raw(const Rcpp::IntegerMatrix& x, std::string method, Rcpp::Nullable<Rcpp::NumericVector> values, Rcpp::List em_options);
RcppExport SEXP _misskappa_rcpp_alpha_raw(SEXP xSEXP, SEXP methodSEXP, SEXP valuesSEXP, SEXP em_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type em_options(em_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_alpha_raw(x, method, values, em_options));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_alpha_available_continuous
Rcpp::List rcpp_alpha_available_continuous(const Rcpp::NumericMatrix& x);
RcppExport SEXP _misskappa_rcpp_alpha_available_continuous(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_alpha_available_continuous(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_fiml_counts
Rcpp::List rcpp_kappa_fiml_counts(const Rcpp::IntegerMatrix& x, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values, int r_total, Rcpp::List em_options);
RcppExport SEXP _misskappa_rcpp_kappa_fiml_counts(SEXP xSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP, SEXP r_totalSEXP, SEXP em_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< int >::type r_total(r_totalSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type em_options(em_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_fiml_counts(x, weight_type, values, r_total, em_options));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fiml_louis_spectrum
Rcpp::List rcpp_fiml_louis_spectrum(const Rcpp::IntegerMatrix& x, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values, Rcpp::List em_options);
RcppExport SEXP _misskappa_rcpp_fiml_louis_spectrum(SEXP xSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP, SEXP em_optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type em_options(em_optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fiml_louis_spectrum(x, weight_type, values, em_options));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_quadratic
Rcpp::List rcpp_kappa_quadratic(const Rcpp::NumericMatrix& x, Rcpp::NumericVector values);
RcppExport SEXP _misskappa_rcpp_kappa_quadratic(SEXP xSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_quadratic(x, values));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_counts
Rcpp::List rcpp_kappa_counts(const Rcpp::IntegerMatrix& x, std::string weight_type, Rcpp::Nullable<Rcpp::NumericVector> values);
RcppExport SEXP _misskappa_rcpp_kappa_counts(SEXP xSEXP, SEXP weight_typeSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_counts(x, weight_type, values));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_continuous
Rcpp::List rcpp_kappa_continuous(const Rcpp::NumericMatrix& x, std::string method, std::string weight_type);
RcppExport SEXP _misskappa_rcpp_kappa_continuous(SEXP xSEXP, SEXP methodSEXP, SEXP weight_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_type(weight_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_continuous(x, method, weight_type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_vector
Rcpp::List rcpp_kappa_vector(const Rcpp::NumericMatrix& x, int features, std::string method, std::string loss_type, Rcpp::NumericVector feature_weights);
RcppExport SEXP _misskappa_rcpp_kappa_vector(SEXP xSEXP, SEXP featuresSEXP, SEXP methodSEXP, SEXP loss_typeSEXP, SEXP feature_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type loss_type(loss_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type feature_weights(feature_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_vector(x, features, method, loss_type, feature_weights));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_gwise_categorical
Rcpp::List rcpp_kappa_gwise_categorical(const Rcpp::IntegerMatrix& x, std::string distance_type, int g, int max_chance_tuples);
RcppExport SEXP _misskappa_rcpp_kappa_gwise_categorical(SEXP xSEXP, SEXP distance_typeSEXP, SEXP gSEXP, SEXP max_chance_tuplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_type(distance_typeSEXP);
    Rcpp::traits::input_parameter< int >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type max_chance_tuples(max_chance_tuplesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_gwise_categorical(x, distance_type, g, max_chance_tuples));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kappa_gwise_continuous
Rcpp::List rcpp_kappa_gwise_continuous(const Rcpp::NumericMatrix& x, std::string distance_type, int g, int max_chance_tuples);
RcppExport SEXP _misskappa_rcpp_kappa_gwise_continuous(SEXP xSEXP, SEXP distance_typeSEXP, SEXP gSEXP, SEXP max_chance_tuplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_type(distance_typeSEXP);
    Rcpp::traits::input_parameter< int >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type max_chance_tuples(max_chance_tuplesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kappa_gwise_continuous(x, distance_type, g, max_chance_tuples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_misskappa_rcpp_kappa_raw", (DL_FUNC) &_misskappa_rcpp_kappa_raw, 5},
    {"_misskappa_rcpp_alpha_raw", (DL_FUNC) &_misskappa_rcpp_alpha_raw, 4},
    {"_misskappa_rcpp_alpha_available_continuous", (DL_FUNC) &_misskappa_rcpp_alpha_available_continuous, 1},
    {"_misskappa_rcpp_kappa_fiml_counts", (DL_FUNC) &_misskappa_rcpp_kappa_fiml_counts, 5},
    {"_misskappa_rcpp_fiml_louis_spectrum", (DL_FUNC) &_misskappa_rcpp_fiml_louis_spectrum, 4},
    {"_misskappa_rcpp_kappa_quadratic", (DL_FUNC) &_misskappa_rcpp_kappa_quadratic, 2},
    {"_misskappa_rcpp_kappa_counts", (DL_FUNC) &_misskappa_rcpp_kappa_counts, 3},
    {"_misskappa_rcpp_kappa_continuous", (DL_FUNC) &_misskappa_rcpp_kappa_continuous, 3},
    {"_misskappa_rcpp_kappa_vector", (DL_FUNC) &_misskappa_rcpp_kappa_vector, 5},
    {"_misskappa_rcpp_kappa_gwise_categorical", (DL_FUNC) &_misskappa_rcpp_kappa_gwise_categorical, 4},
    {"_misskappa_rcpp_kappa_gwise_continuous", (DL_FUNC) &_misskappa_rcpp_kappa_gwise_continuous, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_misskappa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
