// @generated by dev/vendor-cpp.sh from include/misskappa/diagnostics.hpp — DO NOT EDIT; re-run `just vendor`.
#ifndef MISSKAPPA_DIAGNOSTICS_HPP
#define MISSKAPPA_DIAGNOSTICS_HPP

#include "misskappa/estimate.hpp"
#include "misskappa/result.hpp"
#include "misskappa/types.hpp"

#include <cstddef>

namespace misskappa {

// Internal diagnostic surface used by repo experiments. Not part of the
// stable package API.
struct FimlLouisDiagnostic {
  RealVec eigenvalues;               // descending eigenvalues of I_obs.
  RealVec gradient_projection;       // q_k^T grad for Conger's kappa.
  RealVec variance_contribution;     // (q_k^T grad)^2 / lambda_k, zero if dropped.
  double variance = 0.0;
  double lambda_max = 0.0;
  double threshold = 0.0;
  double kappa_conger = 0.0;
  int retained_rank = 0;
  int c = 0;
  int R = 0;
  std::size_t n_subjects = 0;
  std::size_t n_patterns = 0;
};

Result<FimlLouisDiagnostic> diagnose_fiml_louis(
    IntMatView ratings, RealMatView weights, EmOptions opts);

struct FimlGroupedJackknifeDiagnostic {
  RealVec full_estimates;       // Full-sample Cat-FIML estimates.
  RealMat full_vcov;            // Full-sample Cat-FIML covariance.
  RealMat delete_estimates;     // G x 3 delete-group estimates.
  RealVec jackknife_bias;       // (G - 1) * (mean(delete) - full).
  RealVec corrected_estimates;  // full - jackknife_bias.
  RealVec delete_iterations;    // EM iterations used by each delete refit.
  int groups = 0;
  int refits = 0;
  int full_iterations = 0;
  bool hot_start = true;
  std::size_t n_subjects = 0;
  std::size_t n_patterns = 0;
};

Result<FimlGroupedJackknifeDiagnostic> diagnose_fiml_grouped_jackknife(
    IntMatView ratings, RealMatView weights, EmOptions opts,
    int groups, bool hot_start = true);

enum class FimlPenaltyTarget {
  uniform,
  independence,
};

struct FimlPenalizedDiagnostic {
  RealVec estimates;          // Full-sample penalized Cat-FIML estimates.
  RealMat vcov;               // Delete-group jackknife covariance if groups >= 2.
  RealMat delete_estimates;   // G x 3 delete-group estimates.
  RealVec delete_iterations;  // EM iterations used by each delete refit.
  double lambda = 0.0;
  FimlPenaltyTarget target = FimlPenaltyTarget::uniform;
  int groups = 0;
  int refits = 0;
  int full_iterations = 0;
  std::size_t n_subjects = 0;
  std::size_t n_patterns = 0;
};

Result<FimlPenalizedDiagnostic> diagnose_fiml_penalized(
    IntMatView ratings, RealMatView weights, EmOptions opts,
    FimlPenaltyTarget target, double lambda, int variance_groups = 0);

}  // namespace misskappa

#endif  // MISSKAPPA_DIAGNOSTICS_HPP
