// @generated by dev/vendor-cpp.sh from include/misskappa/estimate.hpp — DO NOT EDIT; re-run `just vendor`.
#ifndef MISSKAPPA_ESTIMATE_HPP
#define MISSKAPPA_ESTIMATE_HPP

#include "misskappa/loss.hpp"
#include "misskappa/result.hpp"
#include "misskappa/types.hpp"

#include <cstdint>
#include <vector>

namespace misskappa {

struct EmOptions {
  int max_iter = 10000;
  double tol = 1e-8;
  double prune_tol = 1e-9;   // patterns with theta < prune_tol are dropped.
  double start_alpha = 0.1;  // smoothing on initial theta; small positive.
  double info_rcond = 5e-5;  // Louis eigenvalues <= info_rcond * lambda_max are dropped.
  // Total Dirichlet pseudo-mass spread uniformly over the full C^R pattern
  // table (delta = flatten / C^R added to each cell's expected count in the
  // M-step). With incomplete co-observation of the saturated joint the MLE is
  // a face of the simplex; any flatten > 0 makes the posterior mode unique
  // (the analytic center of that face as flatten -> 0) at the cost of
  // shrinking the fitted table toward uniform with weight
  // flatten / (n + flatten). 0 = strict ML (legacy behaviour, point on the
  // face determined by the deterministic start).
  double flatten = 0.0;
};

struct GwiseOptions {
  // If g <= 0, use all raters (g = R).
  int g = 0;
  // Chance-tuple cap. Categorical g-wise estimators enumerate finite category
  // support; continuous g-wise estimators enumerate direct n^g item tuples.
  std::int64_t max_chance_tuples = 5000000;
};

// --- Categorical raw-rating estimators -------------------------------------
//
// `ratings` is n x R; entries are non-negative integer category codes in
// [0, C-1], or `na_code` (= -1) for missing. `weights` is the C x C
// AGREEMENT matrix (1 on diagonal, partial agreement off-diagonal),
// matching irrCAC's identity.weights / quadratic.weights convention and
// what the misskappa::loss factories return. The estimator computes its
// disagreement coefficients on L = 1 - weights internally.
//
// Estimates returned: (Conger, Fleiss, Brennan-Prediger). Cohen's kappa is
// the R=2 case of Fleiss / Conger. With missing ratings, fixed-rater raw
// coefficients require every rater to be observed and every rater pair to be
// jointly observed by at least one subject; otherwise the saturated pairwise
// functional is not identified and the estimators return Error::not_identified.
Result<Estimation> estimate_available(IntMatView ratings, RealMatView weights);
Result<Estimation> estimate_ipw      (IntMatView ratings, RealMatView weights);
Result<Estimation> estimate_fiml     (IntMatView ratings, RealMatView weights, EmOptions opts);
Result<std::vector<Estimation>> estimate_fiml_many(
    IntMatView ratings, const std::vector<RealMat>& weights, EmOptions opts);
Result<Estimation> estimate_gwet     (IntMatView ratings, RealMatView weights);

// --- Closed-form quadratic estimator (raw, real-valued) --------------------
//
// Moment-based estimator for the quadratically-weighted Cohen / Fleiss /
// Conger / Brennan-Prediger family. Treats categorical ratings as numeric
// scores; missing entries are NaN. Closed form via per-rater means and
// covariances; variance uses the asymptotic covariance of those moments
// with the delta method.
//
// `ratings` is n x R real-valued; `values` is the length-C category-score
// vector used to define the quadratic loss. With missing ratings, every rater
// pair must be jointly observed by at least one subject. Returns (Conger,
// Fleiss, Brennan-Prediger).
Result<Estimation> estimate_quadratic(RealMatView ratings, const RealVec& values);

// --- Counts-format input ---------------------------------------------------
//
// `counts` is n x C of non-negative integers: counts(i, k) is the number of
// raters who assigned subject i to category k. Row sum r_i is the number of
// raters who rated subject i (need not be the same across subjects). Per-
// rater identity is not preserved, so IPW / Gwet (which need rater-specific
// observation rates) are not meaningful here.
//
// Count-data moment weighting. The public R counts estimator uses
// fleiss_cuzick. unit_weighted is kept in the C++ surface for parity studies
// against software that averages each subject's row agreement equally.
enum class CountWeighting {
  fleiss_cuzick,  // row disagreement weight r_i - 1; F&C unequal-judges convention.
  unit_weighted,  // row disagreement weight 1; irrCAC distribution/count convention.
};

// Estimates returned: (Fleiss, Brennan-Prediger). Conger requires identified
// raters and is not in scope for counts. `estimate_available_counts` is the
// Fleiss--Cuzick count moment estimator; use `estimate_counts(...,
// CountWeighting::unit_weighted)` only for comparator/oracle studies. Rows
// with r_i < 2 contain no within-subject pair information and receive zero
// observed-disagreement weight; at least one row with r_i >= 2 is required.
Result<Estimation> estimate_counts(
    IntMatView counts, RealMatView weights, CountWeighting weighting);
Result<Estimation> estimate_available_counts(IntMatView counts, RealMatView weights);

// FIML / EM counterpart of estimate_available_counts. Models the full
// composition (length-C count vector summing to `r_total`) under
// exchangeable iid raters, and uses uniformly-random hypergeometric
// subsampling to relate full counts to observed counts. Each subject's
// observed row sum may be < r_total; FIML weights subjects by how much
// their partial counts pin down the full composition. Returned
// coefficients: (Fleiss, Brennan-Prediger).
//
// Assumption: raters are exchangeable iid from a common distribution.
// Counts data cannot identify rater-specific distributions; for the
// non-exchangeable case use rater-identified data and estimate_fiml.
Result<Estimation> estimate_fiml_counts(
    IntMatView counts, RealMatView weights, int r_total, EmOptions opts);

// --- Continuous-rating estimators -------------------------------------------
//
// `ratings` is n x R of real values; entries that are not finite (NaN or
// +/-Inf) are treated as missing. `loss` is a continuous loss kernel from
// the misskappa::loss continuous factories (identity_loss, linear_loss,
// quadratic_loss, etc.); it returns disagreement in [0, 1] for any pair of
// rating values.
//
// Estimates returned: (Conger, Fleiss). No Brennan-Prediger row — chance
// disagreement against a uniform reference distribution is not meaningful
// without a finite category count. With missing ratings, every rater pair must
// be jointly observed by at least one subject.
Result<Estimation> estimate_available_continuous(RealMatView ratings, loss::ContinuousLoss loss);
Result<Estimation> estimate_ipw_continuous      (RealMatView ratings, loss::ContinuousLoss loss);
Result<Estimation> estimate_gwet_continuous     (RealMatView ratings, loss::ContinuousLoss loss);

// --- Component-separable vector-rating estimators ---------------------------
//
// `ratings` is n x (R * p), with columns ordered rater-major:
//   rater 0 feature 0..p-1, rater 1 feature 0..p-1, ...
// Non-finite entries are missing component ratings. `features` is p.
// `loss` carries diagonal feature weights and a component loss. The estimator
// targets component-separable vector disagreement by summing weighted
// component losses over observed rater-feature overlaps and applying the
// loss transform (identity for Hamming/L1/squared, sqrt for RMS).
//
// Estimates returned: (Conger, Fleiss). Categorical full-pattern FIML and
// non-diagonal feature weights are intentionally out of scope here.
Result<Estimation> estimate_pairwise_vector(
    RealMatView ratings, int features, loss::ComponentSeparableLoss loss);
Result<Estimation> estimate_ipw_vector(
    RealMatView ratings, int features, loss::ComponentSeparableLoss loss);

// --- Coefficient alpha ------------------------------------------------------
//
// `ratings` is n x R with categories in [0, C-1] or `na_code`; `values` is the
// length-C score vector used to turn categories into item scores.
// `ratings_continuous` is n x R with finite item scores and non-finite missing
// entries. The available estimators use pairwise covariance moments and are
// MCAR baselines. The categorical FIML estimator fits the saturated C^R
// full-response distribution by EM and maps it to alpha through the implied
// covariance matrix, so it is intended for small fixed-category batteries.
//
// With missing responses, every item pair must be jointly observed by at least
// one subject. Estimate returned: (alpha).
Result<Estimation> estimate_alpha_available(IntMatView ratings, const RealVec& values);
Result<Estimation> estimate_alpha_available_continuous(RealMatView ratings);
Result<Estimation> estimate_alpha_fiml(
    IntMatView ratings, const RealVec& values, EmOptions opts);

// --- Closed rectangular g-wise estimators -----------------------------------
//
// Complete-data, categorical IPW, and categorical FIML estimators for
// symmetric g-wise disagreement kernels. This is the Frechet / Hubert-style
// multirater-distance family: observed disagreement averages a g-argument
// distance over within-item rater combinations; chance disagreement uses
// Cohen-type (distinct rater combinations) and Fleiss-type (all ordered rater
// tuples) V-statistics.
//
// `estimate_gwise` and `estimate_gwise_continuous` are complete-data only.
// `estimate_ipw_gwise` accepts categorical ratings with `na_code`, and
// `estimate_ipw_gwise_continuous` accepts non-finite missing ratings, under
// the same MCAR IPW convention as the pairwise IPW estimators.
// `estimate_fiml_gwise` fits the saturated categorical full-response
// distribution by EM under ignorable missingness. Estimates returned:
// (Cohen, Fleiss). With missing ratings, every requested rater g-tuple must be
// jointly observed by at least one subject.
Result<Estimation> estimate_gwise(
    IntMatView ratings, loss::GwiseCategoricalDistance distance,
    GwiseOptions opts = {});
Result<Estimation> estimate_ipw_gwise(
    IntMatView ratings, loss::GwiseCategoricalDistance distance,
    GwiseOptions opts = {});
Result<Estimation> estimate_fiml_gwise(
    IntMatView ratings, loss::GwiseCategoricalDistance distance,
    EmOptions em_opts, GwiseOptions gwise_opts = {});
Result<Estimation> estimate_gwise_continuous(
    RealMatView ratings, loss::GwiseContinuousDistance distance,
    GwiseOptions opts = {});
Result<Estimation> estimate_ipw_gwise_continuous(
    RealMatView ratings, loss::GwiseContinuousDistance distance,
    GwiseOptions opts = {});

}  // namespace misskappa

#endif  // MISSKAPPA_ESTIMATE_HPP
