# Generated by Rcpp::compileAttributes-equivalent; hand-written here so
# the R package builds without running compileAttributes during install.

rcpp_kappa_raw <- function(x, method, weight_type, values, em_options) {
  .Call(`_misskappa_rcpp_kappa_raw`, x, method, weight_type, values, em_options)
}
