#!/usr/bin/env Rscript

suppressWarnings({
  .libPaths(c(file.path("code", "analysis", "Rlib"), .libPaths()))
})

suppressPackageStartupMessages({
  library(misskappa)
  library(irrCAC)
})

z <- qnorm(0.975)

fmt <- function(x, digits = 6) formatC(x, format = "f", digits = digits)

data("dat.fleiss1971", package = "misskappa", envir = environment())
x_obs <- as.matrix(dat.fleiss1971)
n_obs <- nrow(x_obs)
r <- max(rowSums(x_obs))
C <- ncol(x_obs)
p <- colSums(x_obs) / (n_obs * r)

method_choices <- eval(formals(misskappa::kappa_counts)$method)
np_method <- if ("available" %in% method_choices) "available" else "np"

fit_m <- misskappa::kappa_counts(x_obs, method = np_method, r = r)
k_m <- as.numeric(fit_m$estimates["Fleiss"])
se_m <- sqrt(as.numeric(fit_m$vcov["Fleiss", "Fleiss"]))
ci_m <- c(k_m - z * se_m, k_m + z * se_m)

fit_i <- irrCAC::fleiss.kappa.dist(x_obs)
k_i <- as.numeric(fit_i$coeff[1])
se_i <- as.numeric(fit_i$stderr[1])
ci_i <- c(k_i - z * se_i, k_i + z * se_i)
ci_i_printed <- as.character(fit_i$conf.int[1])

parse_ci_bounds <- function(ci_str) {
  parts <- gsub("[() ]", "", ci_str)
  pieces <- strsplit(parts, ",", fixed = TRUE)[[1]]
  c(as.numeric(pieces[1]), as.numeric(pieces[2]))
}

ci_i_printed_bounds <- parse_ci_bounds(ci_i_printed)
q_i_printed <- (ci_i_printed_bounds[2] - k_i) / se_i

se_ratio_obs <- se_i / se_m
se_ratio_target_obs <- sqrt(n_obs / (n_obs - 1))

simulate_counts_exchangeable <- function(n, eps) {
  truth <- sample.int(C, n, replace = TRUE, prob = p)
  counts <- matrix(0L, nrow = n, ncol = C)

  for (cc in seq_len(C)) {
    idx <- which(truth == cc)
    m <- length(idx)
    if (m == 0) next

    prob <- eps * p
    prob[cc] <- prob[cc] + (1 - eps)

    counts[idx, ] <- t(rmultinom(m, size = r, prob = prob))
  }
  counts
}

sim_once <- function(n, reps = 2000, seed = 1, kappa_true = k_m) {
  eps <- 1 - sqrt(kappa_true)
  set.seed(seed)

  est_m <- numeric(reps)
  se_m <- numeric(reps)
  cover_m <- logical(reps)

  est_i <- numeric(reps)
  se_i <- numeric(reps)
  cover_i <- logical(reps)

  for (b in seq_len(reps)) {
    counts <- simulate_counts_exchangeable(n, eps)

    fm <- misskappa::kappa_counts(counts, method = np_method, r = r)
    est_m[b] <- as.numeric(fm$estimates["Fleiss"])
    se_m[b] <- sqrt(as.numeric(fm$vcov["Fleiss", "Fleiss"]))
    cover_m[b] <- (est_m[b] - z * se_m[b] <= kappa_true) && (kappa_true <= est_m[b] + z * se_m[b])

    fi <- irrCAC::fleiss.kappa.dist(counts)
    est_i[b] <- as.numeric(fi$coeff[1])
    se_i[b] <- as.numeric(fi$stderr[1])
    cover_i[b] <- (est_i[b] - z * se_i[b] <= kappa_true) && (kappa_true <= est_i[b] + z * se_i[b])
  }

  list(
    n = n,
    reps = reps,
    kappa_true = kappa_true,
    eps = eps,
    se_ratio_target = sqrt(n / (n - 1)),
    misskappa = list(mean_est = mean(est_m), sd_est = sd(est_m), mean_se = mean(se_m), coverage = mean(cover_m)),
    irrCAC = list(mean_est = mean(est_i), sd_est = sd(est_i), mean_se = mean(se_i), coverage = mean(cover_i))
  )
}

sim_30 <- sim_once(30, reps = 2000, seed = 1, kappa_true = k_m)
sim_2000 <- sim_once(2000, reps = 2000, seed = 1, kappa_true = k_m)

out_path <- file.path("notes", "count-form-fleiss1971-irrCAC.tex")

lines <- c(
  "% Auto-generated by code/analysis/fleiss1971_countform_irrCAC_report.R",
  "\\documentclass[11pt]{article}",
  "\\usepackage{amsmath,amssymb,booktabs}",
  "\\usepackage[margin=1in]{geometry}",
  "\\begin{document}",
  "\\section*{Count-form inference sanity check: Fleiss (1971)}",
  "",
  paste0(
    "Package versions: \\texttt{misskappa~", as.character(packageVersion("misskappa")),
    "}, \\texttt{irrCAC~", as.character(packageVersion("irrCAC")), "}."
  ),
  "",
  "\\subsection*{Direct comparison on \\texttt{dat.fleiss1971}}",
  "We compute Fleiss' kappa from Fleiss-form count data and form the same Wald interval",
  "$\\hat\\kappa_F \\pm z_{0.975}\\,\\widehat{\\mathrm{SE}}$ with $z_{0.975}=1.959964$.",
  "",
  "\\begin{center}",
  "\\begin{tabular}{lccc}",
  "\\toprule",
  "Source & $\\hat\\kappa_F$ & $\\widehat{\\mathrm{SE}}$ & Wald 95\\% CI\\\\",
  "\\midrule",
  paste0(
    "misskappa & ", fmt(k_m, 6), " & ", fmt(se_m, 6),
    " & [", fmt(ci_m[1], 6), ", ", fmt(ci_m[2], 6), "]\\\\"
  ),
  paste0(
    "irrCAC & ", fmt(k_i, 6), " & ", fmt(se_i, 6),
    " & [", fmt(ci_i[1], 6), ", ", fmt(ci_i[2], 6), "]\\\\"
  ),
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{center}",
  "",
  paste0(
    "Scaling: the standard errors differ by a factor ",
    fmt(se_ratio_obs, 6),
    ", which equals $\\sqrt{n/(n-1)}=",
    fmt(se_ratio_target_obs, 6),
    "$. This suggests \\texttt{irrCAC} uses a $1/(n-1)$ scaling where \\texttt{misskappa} uses $1/n$."
  ),
  paste0(
    " Also, \\texttt{irrCAC::fleiss.kappa.dist()} prints \\texttt{conf.int = ",
    ci_i_printed,
    "}, which corresponds to an implied quantile ",
    fmt(q_i_printed, 6),
    " (close to $t_{n-1,0.975}=",
    fmt(qt(0.975, df = n_obs - 1), 6),
    "$), rather than $z_{0.975}$."
  ),
  "",
  "\\subsection*{Simulation check (coverage)}",
  "We simulate exchangeable raters with $C=5$ categories and $R=6$ ratings per subject as follows:",
  "draw a latent true label $T_i\\sim\\mathrm{Categorical}(p)$ and then, for each rater,",
  "report $T_i$ with probability $1-\\varepsilon$ and otherwise draw an independent label from $p$.",
  "This implies the population Fleiss kappa equals $\\kappa_F=(1-\\varepsilon)^2$ (independent of $p$).",
  paste0("We set $\\kappa_F=\\hat\\kappa_F$ from \\texttt{dat.fleiss1971} so $\\varepsilon=", fmt(sim_30$eps, 6), "$,"),
  "use $p$ equal to the empirical marginal distribution in \\texttt{dat.fleiss1971},",
  "and evaluate Wald 95\\% CI coverage over 2000 Monte Carlo replicates (seed 1).",
  "",
  "\\begin{center}",
  "\\begin{tabular}{lrrrr}",
  "\\toprule",
  "Setting & Mean($\\hat\\kappa_F$) & SD($\\hat\\kappa_F$) & Mean(SE) & Coverage\\\\",
  "\\midrule",
  paste0(
    "$n=30$ (misskappa) & ", fmt(sim_30$misskappa$mean_est, 6),
    " & ", fmt(sim_30$misskappa$sd_est, 6),
    " & ", fmt(sim_30$misskappa$mean_se, 6),
    " & ", fmt(sim_30$misskappa$coverage, 4), "\\\\"
  ),
  paste0(
    "$n=30$ (irrCAC) & ", fmt(sim_30$irrCAC$mean_est, 6),
    " & ", fmt(sim_30$irrCAC$sd_est, 6),
    " & ", fmt(sim_30$irrCAC$mean_se, 6),
    " & ", fmt(sim_30$irrCAC$coverage, 4), "\\\\"
  ),
  paste0(
    "$n=2000$ (misskappa) & ", fmt(sim_2000$misskappa$mean_est, 6),
    " & ", fmt(sim_2000$misskappa$sd_est, 6),
    " & ", fmt(sim_2000$misskappa$mean_se, 6),
    " & ", fmt(sim_2000$misskappa$coverage, 4), "\\\\"
  ),
  paste0(
    "$n=2000$ (irrCAC) & ", fmt(sim_2000$irrCAC$mean_est, 6),
    " & ", fmt(sim_2000$irrCAC$sd_est, 6),
    " & ", fmt(sim_2000$irrCAC$mean_se, 6),
    " & ", fmt(sim_2000$irrCAC$coverage, 4), "\\\\"
  ),
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{center}",
  "",
  paste0(
    "Both implementations agree closely; in particular, their mean standard errors differ by a factor very close to ",
    "$\\sqrt{n/(n-1)}$ (e.g., for $n=30$, ",
    fmt(sim_30$irrCAC$mean_se / sim_30$misskappa$mean_se, 6),
    " vs ",
    fmt(sim_30$se_ratio_target, 6),
    ")."
  ),
  "For $n=30$ the (normal-quantile) Wald intervals undercover (around 0.92--0.93 in this experiment), consistent with small-sample bias and/or normal approximation error.",
  "For $n=2000$ the coverage is close to nominal for both.",
  "",
  "\\end{document}"
)

dir.create(dirname(out_path), showWarnings = FALSE, recursive = TRUE)
writeLines(lines, out_path)
cat("Wrote ", out_path, "\n", sep = "")
