#!/usr/bin/env Rscript

suppressWarnings({
  .libPaths(c(file.path("code", "analysis", "Rlib"), .libPaths()))
})

suppressPackageStartupMessages({
  library(misskappa)
})

fmt <- function(x, digits = 4) formatC(x, format = "f", digits = digits)

as_numeric_matrix <- function(x) {
  x_mat <- as.matrix(x)
  storage.mode(x_mat) <- "integer"
  x_mat
}

fit_summary <- function(fit) {
  est <- coef(fit)
  se <- sqrt(diag(vcov(fit)))
  out <- data.frame(
    estimate = as.numeric(est),
    se = as.numeric(se),
    row.names = names(est)
  )
  out
}

latex_escape <- function(s) {
  s <- gsub("\\\\", "\\\\textbackslash{}", s)
  s <- gsub("([%&#_$])", "\\\\\\1", s, perl = TRUE)
  s
}

to_latex_table <- function(df, caption = NULL, label = NULL) {
  stopifnot(is.data.frame(df))

  cn <- colnames(df)
  rn <- rownames(df)
  if (is.null(rn) || any(rn == "")) rn <- as.character(seq_len(nrow(df)))

  header <- c(
    "\\begin{table}[!ht]",
    "\\centering",
    "\\small",
    "\\setlength{\\tabcolsep}{5pt}",
    if (!is.null(caption)) paste0("\\caption{", caption, "}"),
    if (!is.null(label)) paste0("\\label{", label, "}"),
    paste0("\\begin{tabular}{l", paste(rep("rr", length(cn) / 2), collapse = ""), "}"),
    "\\toprule",
    paste(c(" ", cn), collapse = " & "), "\\\\",
    "\\midrule"
  )

  body <- character()
  for (i in seq_len(nrow(df))) {
    row <- df[i, , drop = FALSE]
    body <- c(body, paste(c(rn[i], fmt(row[[1]]), fmt(row[[2]]), fmt(row[[3]]), fmt(row[[4]]), fmt(row[[5]]), fmt(row[[6]])), collapse = " & "), "\\\\")
  }

  footer <- c(
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )

  c(header, body, footer)
}

# --- Data ---
data("dat.gwet2014", package = "misskappa", envir = environment())
data("dat.klein2018", package = "misskappa", envir = environment())
data("dat.zapf2016", package = "misskappa", envir = environment())
data("dat.fleiss1971", package = "misskappa", envir = environment())

x_gwet <- as_numeric_matrix(dat.gwet2014)
x_klein <- as_numeric_matrix(dat.klein2018)
x_zapf <- as_numeric_matrix(dat.zapf2016)

fits <- list(
  "AC" = kappa_raw(x_gwet, method = "available", weight = "identity"),
  "IPW" = kappa_raw(x_gwet, method = "ipw", weight = "identity"),
  "Gwet" = kappa_raw(x_gwet, method = "gwet", weight = "identity")
)

summaries <- lapply(fits, fit_summary)

make_method_row <- function(sum_df) {
  c(
    Conger_est = sum_df["Conger", "estimate"],
    Conger_se = sum_df["Conger", "se"],
    Fleiss_est = sum_df["Fleiss", "estimate"],
    Fleiss_se = sum_df["Fleiss", "se"],
    BP_est = sum_df["Brennan-Prediger", "estimate"],
    BP_se = sum_df["Brennan-Prediger", "se"]
  )
}

tab <- do.call(rbind, lapply(summaries, make_method_row))
tab <- as.data.frame(tab)
colnames(tab) <- c(
  "$\\hat\\kappa_C$", "SE",
  "$\\hat\\kappa_F$", "SE",
  "$\\hat\\kappa_{BP}$", "SE"
)

out_tex <- file.path("notes", "misskappa-package-example.tex")
dir.create(dirname(out_tex), showWarnings = FALSE, recursive = TRUE)

lines <- c(
  "% Auto-generated by code/analysis/misskappa_package_example.R",
  "\\documentclass[11pt]{article}",
  "\\usepackage{amsmath,amssymb,booktabs}",
  "\\usepackage[margin=1in]{geometry}",
  "\\begin{document}",
  "\\section*{The \\texttt{misskappa} package (draft)}",
  "",
  "\\texttt{misskappa} is an R package for estimation and inference for weighted multi-rater agreement coefficients,",
  "including Conger's $\\kappa_C$, Fleiss' $\\kappa_F$, and the Brennan--Prediger coefficient.",
  "It supports raw rating matrices (subjects $\\times$ raters) and count-form data, and allows missing ratings (\\texttt{NA}).",
  "",
  "\\paragraph{Main user-facing functions.}",
  "\\begin{itemize}",
  "\\item \\texttt{kappa\\_raw(x, method, weight)}: categorical ratings in raw format (allows \\texttt{NA}).",
  "\\item \\texttt{kappa\\_counts(x, method, weight, r)}: Fleiss-form counts (subjects $\\times$ categories).",
  "\\item \\texttt{kappa\\_continuous(x, method, weight)}: continuous ratings (allows \\texttt{NA}).",
  "\\item \\texttt{kappa(x, type = \"auto\", ...)}: convenience dispatcher.",
  "\\end{itemize}",
  "",
  "\\paragraph{Included example datasets.}",
  "\\begin{itemize}",
  paste0(
    "\\item \\texttt{dat.gwet2014}: raw $n\\times R$ ratings with missing values (dim ",
    nrow(x_gwet), "\\,$\\times$\\,", ncol(x_gwet), "; ",
    "NAs=", sum(is.na(x_gwet)), ")."
  ),
  paste0(
    "\\item \\texttt{dat.klein2018}: raw $n\\times R$ ratings with missing values (dim ",
    nrow(x_klein), "\\,$\\times$\\,", ncol(x_klein), "; ",
    "NAs=", sum(is.na(x_klein)), ")."
  ),
  paste0(
    "\\item \\texttt{dat.zapf2016}: raw $n\\times R$ ratings (complete) (dim ",
    nrow(x_zapf), "\\,$\\times$\\,", ncol(x_zapf), "; ",
    "NAs=", sum(is.na(x_zapf)), ")."
  ),
  paste0(
    "\\item \\texttt{dat.fleiss1971}: Fleiss-form counts (dim ",
    nrow(dat.fleiss1971), "\\,$\\times$\\,", ncol(dat.fleiss1971), ")."
  ),
  "\\end{itemize}",
  "",
  "\\section*{Example: missing ratings (\\texttt{dat.gwet2014})}",
  "Below is a minimal example (nominal/identity weights) using the three incomplete-data estimators used in the paper: available-case (AC), IPW, and Gwet.",
  "",
  "\\begin{verbatim}",
  "library(misskappa)",
  "data(dat.gwet2014)",
  "x <- as.matrix(dat.gwet2014)",
  "",
  "kappa_raw(x, method = \"available\", weight = \"identity\")",
  "kappa_raw(x, method = \"ipw\",       weight = \"identity\")",
  "kappa_raw(x, method = \"gwet\",      weight = \"identity\")",
  "\\end{verbatim}",
  "",
  to_latex_table(
    tab,
    caption = "Agreement estimates and asymptotic standard errors for \\texttt{dat.gwet2014} (identity weights).",
    label = "tab:misskappa-gwet2014-example"
  ),
  "",
  "\\textit{Note.} All \\texttt{kappa\\_*} functions return a \\texttt{misskappa\\_estimate} object with point estimates (\\texttt{coef()})",
  "and an asymptotic variance--covariance matrix (\\texttt{vcov()}).",
  "",
  "\\end{document}"
)

writeLines(lines, out_tex)
cat("Wrote ", out_tex, "\n", sep = "")

if (Sys.getenv("SIM_COMPILE", "1") == "1") {
  args <- c("-interaction=nonstopmode", "-halt-on-error", "-output-directory", "notes", out_tex)
  status1 <- system2("pdflatex", args = args)
  status2 <- system2("pdflatex", args = args)
  if (!identical(status1, 0L) || !identical(status2, 0L)) {
    stop("pdflatex failed (exit codes ", status1, ", ", status2, ")")
  }
  cat("Compiled notes/misskappa-package-example.pdf\n")
}
